### ISSUE TITLE
Old www2-pcmdi.llnl.gov URLs are dead

### ISSUE THREAD

**Issue by durack1** [PCMDI/pcmdi.github.io#1]
I've just gone to find a couple of the `cdms2` user pages on the web and these are now dead links:

http://pcmdi.github.io/cdat/quick_reference/cdms
http://pcmdi.github.io/cdat/manuals/cdms_v4.0_html/ch2_cdms_4.0.html
http://pcmdi.github.io/cdat/tutorials/advanced_cdat/comparing_datasets.html

It appears the previous URLs, e.g. www2-pcmdi.llnl.gov are autoforwarding to pcmdi.github.io

@mattben @doutriaux1 @dnadeau4 - these were useful pages, it'd be great if the links auto-forwarded to revised and currently hosted information

**Comment by durack1** [comment]
@mattben this is also true for the links:
http://uv-cdat.github.io/cdat-site/cdms.selectors.html
http://uv-cdat.github.io/cdms.selectors.html

**Comment by dnadeau4** [comment]
@durack1  @mattben  I found this cool web site.  I am not sure where the other pages are or how to access github.io...

http://library.wmo.int/opac/index.php?lvl=notice_display&id=16300#.VcUtSpMy3dF

**Comment by doutriaux1** [comment]
but it's not our cdms though :wink:

**Comment by dnadeau4** [comment]
You are right, but the article looks very cool!  :smile:

**Comment by durack1** [comment]
This is also "interesting" http://nullege.com/codes/search/cdms2.MV.reshape

**Comment by durack1** [comment]
The above seems to be the only location where `cdms2.selectors` documentation can be currently found.. Or is it?

**Comment by dnadeau4** [comment]
Very nice link!

**Comment by mattben** [comment]
What about the way back machine? Are these pages missing or just the links are broken? If the links are broken what should they point to?

**Comment by durack1** [comment]
@mattben very good questions, the links that I hit problems with are included in the [top comment](https://github.com/PCMDI/pcmdi.github.io/issues/1#issue-99314047):
http://pcmdi.github.io/cdat/quick_reference/cdms
http://pcmdi.github.io/cdat/manuals/cdms_v4.0_html/ch2_cdms_4.0.html
http://pcmdi.github.io/cdat/tutorials/advanced_cdat/comparing_datasets.html

Not sure what the state of migration was back in 2015 when this issue was originally created.. I wonder if a spider of the PCMDI website could uncover dead links that need to either be redirected or the content edited?

**Comment by mattben** [comment]
@durack1 @dnadeau4 @doutriaux1 @taylor13 

This question popped up again yesterday. 
* Have these pages been found?
* Do we have correct urls?
* Have the pages in this repo been updated with the correct information?
* Is this still a pcmdi.github.io issues or a general PCMDI documentation issue?

**Comment by doutriaux1** [comment]
@mattben tony restarted the server pcmdi2 yesterday. We need to convert all of this to jupyter notebook. @williams13 can we get an intern for this?

**Comment by durack1** [comment]
@doutriaux1 @mattben I like the idea of the old server `www-pcmdi.llnl.gov` being hidden, but available from `old-pcmdi.llnl.gov`, I wonder how easy it would be to also host the `www2-pcmdi` stuff somewhere, or even better pull all that old content into the new site `pcmdi.llnl.gov` or integrate it better across the pcmdi and the (uv-)cdat webpages.. There is some really useful content hidden on `www2-pcmdi` so it'd be great to make sure it persists (and is much easier to find and more logically organized)

**Comment by durack1** [comment]
@mattben not sure I am the correct assignee, I think this is up to you..

**Comment by durack1** [comment]
@mauzey1 I believe all the webpages linked above are no longer useful (CDAT is no longer supported), and don't exist, so I will close this issue
