### ISSUE TITLE
Review webserver defaults

### ISSUE THREAD

**Issue by durack1** [PCMDI/pcmdi.github.io#113]
It seems that some of the apache webserver defaults should be revised so that directory listings like the below don't occur
![pcmdiwebstaffdir](https://cloud.githubusercontent.com/assets/3229632/23522768/22ada5d2-ff39-11e6-93dc-592214b03880.png)

**Comment by mattben** [comment]
updated /etc/httpd/conf/httpd.conf removing Indexes for directories.
http://pcmdiweb.llnl.gov/staff/
