### ISSUE TITLE
pcmdiweb -> pcmdi.llnl.gov switchover, new nav links

### ISSUE THREAD

**Issue by durack1** [PCMDI/pcmdi.github.io#114]
Speaking to @sashakames this morning, the timeline for the switch over from [https://pcmdi.llnl.gov/projects/esgf-llnl/](https://pcmdi.llnl.gov/projects/esgf-llnl/) to [https://esgf-node.llnl.gov/projects](https://esgf-node.llnl.gov/projects) have been set for Monday 20th March 2017, with a two week redirect before finalizing the final URLs on the Monday 3rd April 2017.

During and after this changeover we'll need prominent links on the PCMDI homepage so that users can find the ESGF search page when they hit [https://pcmdi.llnl.gov/](https://pcmdi.llnl.gov/)

So we need:
- [x] ESGF links in the navbar
- [x] ESGF link/button in the transitioning box

@taylor13 @mattben @hoang1 @dnadeau4 @williams13

**Comment by mattben** [comment]
Do you want this in the nav bar or in an announcement box? example http://uvcdat.llnl.gov

**Comment by durack1** [comment]
@mattben I think both, so a navbar entry (that will remain long term) and another button in the existing announcement box (alongside "old site" and "report issues")

**Comment by durack1** [comment]
@sashakames the placeholder links are now in place http://pcmdiweb.llnl.gov/

**Comment by durack1** [comment]
@sashakames @mattben @taylor13 I think we're good to close this
