### ISSUE TITLE
pcmdiweb SSL

### ISSUE THREAD

**Issue by mattben** [PCMDI/pcmdi.github.io#121]
- [x] update server ssl cert
- [x] configure server to use https
- [x] verify https://pcmdiweb.llnl.gov (@mattben, @durack1, @williams13)
- [x] verify http://pcmdiweb.llnl.gov (should redirect to https) (@mattben, @durack1, @williams13)
- [x] set up pcmdi redirect
- [x] verify cmip6 files are accessible

**Comment by durack1** [comment]
@mattben @williams13 not sure what I need to do here?

**Comment by mattben** [comment]
@durack1 @willams13 just updated the issues, I need @durack1 to test the urls worked for him too, and I just received your email stating that they did.

**Comment by durack1** [comment]
@mattben @taylor13 @williams13 the URLs we were getting heat from overseas is now working, it's https://pcmdi.llnl.gov/CMIP6/TermsOfUse
