### ISSUE TITLE
Setup URL forwarding for www.pcmdi.llnl.gov -> pcmdi.llnl.gov

### ISSUE THREAD

**Issue by durack1** [PCMDI/pcmdi.github.io#123]
Currently https://www.pcmdi.llnl.gov/ doesn't forward to https://pcmdi.llnl.gov/. It would be great if it did to smooth the transition from the old https://www-pcmdi.llnl.gov/ to the new site

**Comment by James-Crean** [comment]
@mattben I believe someone mentioned in the meeting this week that lab sites were previously not allowed to use www.*

Is that still the case?

**Comment by durack1** [comment]
@James-Crean @mattben if it is the case, then I suggest we just catch and redirect all www.* instances as many folks still append it

**Comment by durack1** [comment]
@mattben can the www.* also be added to the global redirect? It seems it's not working, whereas www-* etc is working great

**Comment by durack1** [comment]
@mauzey1 is this easy to do? Will it require some DNS registration forwards?

**Comment by mauzey1** [comment]
@durack1 @sashakames Do we have any websites in PCMDI, ESGF, or AIMS that do a redirect from www.*?

**Comment by durack1** [comment]
@mauzey1 nope, the only redirect that I know about is the old https://www-pcmdi.llnl.gov/ redirecting to https://pcmdi.llnl.gov/?

**Comment by durack1** [comment]
@mauzey1 can we address this, or is the lab www* policy still in place restricting action?

**Comment by durack1** [comment]
Closing as per below, thanks @mauzey1:

From: ServiceNow
Date: Thursday, October 20, 2022 at 10:57 AM
To: Durack, Paul J.
Subject: Request Item RITM0738710 - Support Request has been opened on your behalf

This requested item has been opened on your behalf
 
Click here to view Request: [RITM0738710](https:/llnl.servicenowservices.com/ess?id=ticket&table=sc_req_item&sys_id=fdaaa75f1b66d5d08f8c4000f54bcb10)
Requested Item Number: RITM0738710
Opened: 2022-10-20 10:56:40 PDT
Requested For: Christopher Mauzey (mauzey1)
Requested By: Christopher Mauzey (mauzey1)
Opened By: David Lehr (lehr4)
Item: Support Request
RITM0738710: 1 X Support Request at $0.00 each 
Options:
     Transferred from Call = CALL0823676
     Requested by = Christopher Mauzey (mauzey1)
     Requested for = Christopher Mauzey (mauzey1)
     Desktop Support = Science and Technology
     Redirect notification to = Paul Durack (durack1)
     Service = Domain Name System (DNS)
     Request type = DNS Data Change
     RITM Assignment Group = DNS_DHCP Support Team
     Location where work is to be performed = B17xx Rx
     Configuration item filter = Requested for
     Skip approvals = false
     Override steps (Description -> Task description) = false
     Assign to me = false
     Close complete = false
     Short description = Redirect https://www.pcmdi.llnl.gov/ to pcmdi.llnl.gov
     Comments = 2022-10-20 10:54:30 - Christopher Mauzey (mauzey1) (Additional comments)
Network & Connectivity, Domain Name System (DNS), Institutional, Domain Name System (DNS)

Due date = 2022-10-24 18:00:00 PDT
