### ISSUE TITLE
Create CMIP6 guide page

### ISSUE THREAD

**Issue by durack1** [PCMDI/pcmdi.github.io#124]
@taylor13 the document at https://goo.gl/5k4Hln will need to be migrated to the CMIP6 site

@durack1 will start the process, as there is a urgency to get this information live

**Comment by taylor13** [comment]
Can you wait 25 more minutes?  Consulting with Denis on this.
Karl

**Comment by durack1** [comment]
@taylor13 the first page is live - we then need to determine how many subpages are generated

https://pcmdi.llnl.gov/CMIP6/Guide/

**Comment by taylor13** [comment]
We should only link to the first of the 3 parts; the others aren't ready.

**Comment by durack1** [comment]
@taylor13 have to go and pickup the car.. Will give you a call in a hour to see what can be copied to the web - the placeholder pages are now live https://pcmdi.llnl.gov/CMIP6/Guide/

**Comment by taylor13** [comment]
@durack1 I think we should post the present version of the guide (1st part), but with comments removed.  O.K.?

**Comment by durack1** [comment]
@taylor13 sure will do so now..
