### ISSUE TITLE
Missing content for metrics page

### ISSUE THREAD

**Issue by James-Crean** [PCMDI/pcmdi.github.io#170]
The page at http://pcmdi.github.io/research/metrics/ has no content.

![screen shot 2017-09-12 at 5 15 56 pm](https://user-images.githubusercontent.com/3454070/30353930-2685ef28-97de-11e7-9d30-ccc934e6c07b.png)

**Comment by durack1** [comment]
@James-Crean another good ping, I'll assign @gleckler1 to drop some placeholder text here

We can close once the text is in place

**Comment by mauzey1** [comment]
The metrics page has now been filled out by https://github.com/PCMDI/pcmdi.github.io/pull/285
