### ISSUE TITLE
Missing guides for CMIP6

### ISSUE THREAD

**Issue by James-Crean** [PCMDI/pcmdi.github.io#171]
The bottom two guides "For CMIP6 ESGF data node managers and operators" and "For Users of CMIP6 model output" do not have content. 
![screen shot 2017-09-12 at 5 25 04 pm](https://user-images.githubusercontent.com/3454070/30354139-914932f6-97df-11e7-843a-1bb0e901cc5a.png)

**Comment by durack1** [comment]
@James-Crean thanks, we're (@taylor13 and I are) in the process of generating that content with community input in a google doc format. Once it's complete, it will be migrated over to the markdown format

We can leave this issue open until we have the content in place
