### ISSUE TITLE
cmip-pcmdi.llnl.gov down?

### ISSUE THREAD

**Issue by James-Crean** [PCMDI/pcmdi.github.io#173]
A link referencing https://cmip-pcmdi.llnl.gov/cmip5/docs/CMIP5_output_metadata_requirements.pdf?id=1 is broken. Is this site down for good or is this temporary?

The link is question is located at: https://pcmdi.github.io/CMIP6/Guide/modelers.html#5-model-output-requirements

Look for " CMIP5 requirements" under section 5. Model output requirements.

**Comment by durack1** [comment]
@James-Crean thanks, another catch.

@hoang1 is currently trying to get the old webserver (`rainbow`) back up, this is the home of http://www-pcmdi.llnl.gov, http://cmip-pcmdi.llnl.gov and a number of other sites.. My hope is these will be live very soon, as the www-pcmdi is still our "current" website

**Comment by James-Crean** [comment]
Ah, makes sense that they would be on the same server. Let's leave this open until that content is moved over to the new site.

**Comment by durack1** [comment]
@James-Crean this is now resolved as both URLs are now live, I will close
