### ISSUE TITLE
CMIP3 page

### ISSUE THREAD

**Issue by James-Crean** [PCMDI/pcmdi.github.io#175]
Regarding the page at: https://pcmdi.github.io/mips/cmip3

The first two links labeled "World Climate Research Programme’s" and "Working Group on Coupled Modelling" lead to a 404 page. 

The "ESG data portal" link also appears to refer to a website that is down.

**Comment by durack1** [comment]
@James-Crean the "ESG data portal" should be revised to "ESGF data portal" and the URL is https://esgf-node.llnl.gov

"World Climate Research Programme's" should point to https://www.wcrp-climate.org/

"Working Group on Coupled Modeling" should point to https://www.wcrp-climate.org/wgcm-overview

**Comment by James-Crean** [comment]
Does https://esgf-node.llnl.gov/ load for you? It loads endlessly for me.

**Comment by durack1** [comment]
@James-Crean yep, it redirects instantly to https://esgf-node.llnl.gov/projects/esgf-llnl/

**Comment by durack1** [comment]
Are you on IE or Chrome?

**Comment by James-Crean** [comment]
Both chrome and Firefox load forever. This is a separate issue though, since the site does work for you.
