### ISSUE TITLE
Research Highlights Page - dead links

### ISSUE THREAD

**Issue by James-Crean** [PCMDI/pcmdi.github.io#184]
Page: https://pcmdi.llnl.gov/research/researchHighlights.html

The following external links report 404 not found:

2013
Program for Climate Model Diagnosis and Intercomparison (PCMDI) fact sheet

2011
Ben Santer elected to membership in the National Academy of Sciences

**Comment by durack1** [comment]
> 2011
> Ben Santer elected to membership in the National Academy of Sciences

Try here: http://www.nasonline.org/member-directory/members/3008403.html

> 2013
> Program for Climate Model Diagnosis and Intercomparison (PCMDI) fact sheet

https://web.archive.org/web/20141225022241/climatemodeling.science.energy.gov/f/Fact_Sheets/PCMDI_Fact_Sheet.pdf

It also looks like wikipedia needs an update if you're keen.. https://en.wikipedia.org/wiki/Program_for_Climate_Model_Diagnosis_and_Intercomparison
