### ISSUE TITLE
About page broken links

### ISSUE THREAD

**Issue by James-Crean** [PCMDI/pcmdi.github.io#185]
Page: https://pcmdi.llnl.gov/about.html

The following external links are broken:

* WCRP metrics panel - link: http://www-metrics-panel.llnl.gov/wiki
* Regional and Global Climate Modeling (RGCM) - link: http://www.er.doe.gov/ober/CESD/regional.html
* Office of Biological and Environmental Research (BER) - link: 
http://www.er.doe.gov/ober/ober_top.html
* Climate and Environmental Sciences Division - link: http://www.er.doe.gov/ober/CESD_top.html

**Comment by durack1** [comment]
> WCRP metrics panel

https://www.wcrp-climate.org/wgcm/WGCM16/Metrics_Panel.pdf

> Regional and Global Climate Modeling (RGCM)

https://science.energy.gov/ber/research/cesd/regional-and-global-modeling/

> Office of Biological and Environmental Research (BER)

https://science.energy.gov/ber

> Climate and Environmental Sciences Division

https://science.energy.gov/ber/research/cesd

**Comment by James-Crean** [comment]
Awesome, thanks for the quick response!

**Comment by durack1** [comment]
It's easy when you know where to look!
