### ISSUE TITLE
Publication page links

### ISSUE THREAD

**Issue by James-Crean** [PCMDI/pcmdi.github.io#186]
The following publications have DOI's that do not exist/have been removed. Hopefully this is just a small matter of finding the new DOI for the publication in question. 

Page: https://pcmdi.llnl.gov/publications.html

http://dx.doi.org/10.1073/pnas1305332110
http://dx.doi/org/10.1002/asi.378
http://dx.doi.org/24.10.1109/MCSE.2011.77
http://ptonline.aip.org/journals/doc/PHTOAD-ft/vol_62/iss_1/48_1.shtml
http://dx.doi.org/10.1175/2008CLI2231.1
http://dx.doi.oeg/10.1007/s10584-007-9374-9
http://dx.doi.org/10.1017/CB09780511619472.004
http://dx.doi.org/10.1038/nature 03209

**Comment by durack1** [comment]
Looks like a couple of the above are just badly formed, spaces for e.g. (the nature03209), or bad urls e.g. dx.doi.oeg vs .org, wrong . vs / e.g. http://dx.doi/org etc..

A google search for the title should give you the correct URL
