### ISSUE TITLE
Redirect from pcmdiweb

### ISSUE THREAD

**Issue by James-Crean** [PCMDI/pcmdi.github.io#187]
https://pcmdiweb.llnl.gov/mips/cmip/about-cmip.html (found using google) gives a 404. This might be something we can redirect to: https://pcmdi.llnl.gov/mips/cmip/about-cmip.html

**Comment by durack1** [comment]
@James-Crean agreed.

All the pcmdiweb.llnl.gov hard-coded URLs should be switched out for pcmdi.llnl.gov (pcmdiweb was the original URL, before pcmdi.llnl.gov became esgf-node.llnl.gov)

**Comment by mattben** [comment]
in regards to the 404 error that is gone, the cert was updated.
I agree that anything pcmdiweb.llnl.gov should be redirected to pcmdi.llnl.gov 
I updated http.conf and now pcmdiweb redirects to pcmdi.
