### ISSUE TITLE
about-cmip broken links

### ISSUE THREAD

**Issue by James-Crean** [PCMDI/pcmdi.github.io#188]
Page: https://pcmdi.llnl.gov/mips/cmip/about-cmip.html

Under "C4MIP: Coupled Carbon Cycle Climate Model Intercomparison Project"

Both the "homepage" and "Protocol and forcing fields" links are broken. 

 http://www.c4mip.cnrs-gif.fr does not seem to be up anymore.

**Comment by durack1** [comment]
C4MIP should be https://www.wcrp-climate.org/modelling-wgcm-mip-catalogue/modelling-wgcm-mips/160-unifying-themes/unifying-themes-modelling/modelling-wgcm/modelling-wgcm-cmip6/1050-modelling-cmip6-c4mip

All the other MIPs can be found at https://www.wcrp-climate.org/modelling-wgcm-mip-catalogue/modelling-wgcm-cmip6-endorsed-mips
