### ISSUE TITLE
diagnostic_subprojects page

### ISSUE THREAD

**Issue by James-Crean** [PCMDI/pcmdi.github.io#193]
Page: https://pcmdi.llnl.gov/ipcc/diagnostic_subprojects.html

Every "Abstract" link is broken. The page they all lead to is dynamically created on the old site by php. We can certainly dump the database and create individual pages for each abstract, but it would be a bit time consuming and I am not sure how much value is added by having the abstracts linked and/or hosted by us. (Copy and pasting the title into google almost always pulls up the same abstract, for instance)

Thoughts?
![screen shot 2017-09-15 at 4 44 14 pm](https://user-images.githubusercontent.com/3454070/30507178-e308cc38-9a36-11e7-891e-cc9be408477c.png)

**Comment by durack1** [comment]
@James-Crean as many of these already appear to have a valid DOI link, would it be easiest to add in a DOI entry for those that don't have it, and then purge the "Abstract" files/php altogether? I think this solution is best, as we keep the link to the information, it's just the information is not locally available. The "full Article" links can also be turfed, as the DOI links provide exactly what we want

Do you agree?

**Comment by James-Crean** [comment]
Sounds good to me. Thanks Paul!

**Comment by mauzey1** [comment]
Abstract links have been removed.  Closing issue.
