### ISSUE TITLE
link to cmip5 website is incorrect on this page:https://www.wcrp-climate.org/wgcm-cmip/wgcm-cmip5, as it goes to https://pcmdi.llnl.gov/cmip5/index.html?submenuheader=0

### ISSUE THREAD

**Issue by takurkowski** [PCMDI/pcmdi.github.io#196]

**Comment by mattben** [comment]
who is the maintainer of https://www.wcrp-climate.org/wgcm-cmip/wgcm-cmip5?
The error is in an apache config that is miss handling the redirect. I will look in to this today.
The page you are looking for I believe is https://pcmdi.llnl.gov/mips/cmip5/ 

A future issue will be that most the old site www-pcmdi.llnl.gov and cmip-pcmdi.llnl.gov urls do not match up with the new site. The resolution i'm hoping to put in place is to stop users from seeing that 404 Not Found page, but will still leave them in some confusion as the link they are expecting to take them to a specific page will take them to the home page of the new site.

**Comment by mattben** [comment]
awesome super hack in place to catch all old urls 
* www-pcmdi.llnl.gov/*
*  pcmdi-cmip.llnl.gov/*
* cmip-pcmdi.llnl.gov/*

to the home page of the new pcmdi.llnl.gov
