### ISSUE TITLE
www-pcmdi.llnl.gov certificate issue

### ISSUE THREAD

**Issue by durack1** [PCMDI/pcmdi.github.io#2]
@mattben @taylor13 as per screen grab - it seems the website has some major certificate issues:
![151209_www-pcmdidotllnldotgov-certerror](https://cloud.githubusercontent.com/assets/3229632/11697989/5ebbe0d6-9e71-11e5-9fbf-ef6340855498.png)

**Comment by taylor13** [comment]
Which website?  What link(s) is (are) broken?

**Comment by durack1** [comment]
It's not a link - it's the certificates for the server, so accessing the site externally leads to security warnings being triggered and modern browsers blocking the connection

**Comment by mattben** [comment]
@durack1 are you on the lab network? I"m currently VPN'd in to LLNL (Yellow Network)  and I don't get any errors with Safari, Firefox, or Chrome.

**Comment by durack1** [comment]
@mattben yep exactly, I'm outside the network.. So am hitting those issues, as would everyone else external.. Kinda concerning, not sure how long this issue has been a problem

**Comment by mattben** [comment]
agh ok. Sorry so yes `https://www-pcmdi.llnl.gov` has a cert issue, which I do believe. This server does not have a certified signed certificate. `http://www-pcmdi.llnl.gov` works as expected.

**Comment by mattben** [comment]
Options:
1. Redirect `https` to `http`
2. Buy a certified signed certificate*.

*We have bought them for our others servers there about $200 a year.

**Comment by durack1** [comment]
@mattben yep, whoops sorry I should have made the `https` explicit..

I think in the interim, try the `https` -> `http` redirect - I can test this as soon as it's implemented from outside the network..

**Comment by durack1** [comment]
@mattben most modern browsers try to push toward `https` more often than not.. In particular my experience with `Firefox 40+` it seems all connections try for `https` as a first try..

**Comment by mattben** [comment]
on a side note, pcmdi.llnl.gov gives me the same error in Safari because of there self signed certs. This issues could also be being passed down from the parent site (pcmdi.llnl.gov)

**Comment by mattben** [comment]
on this topic, all lab servers must connect over https soon/already. Tony and I have the cert and are working on this (on the new server)

**Comment by mattben** [comment]
This is now a non issues as the site has already been moved to a new server, and will be receiving its proper url of pcmdi.llnl.gov asap. Using the alt-name field in the SSL Cert we should have not issues moving forward once the corrected url is in place. If a issues does arise lets open a new clean issues in regards to that issues.
