### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by ErikaWarnatzsch** [PCMDI/pcmdi.github.io#203]
Link to:  [http://www-pcmdi.llnl.gov/about/staff/Taylor/CV/Taylor_diagram_primer.pdf](url) on this page: [http://davidcarslaw.github.io/openair/reference/TaylorDiagram.html](url) is broken. 

It is meant to provide details of a taylor diagram

**Comment by durack1** [comment]
@ErikaWarnatzsch the website was recently reformatted, you'll find at that file at the URL https://pcmdi.llnl.gov/staff/taylor/CV/Taylor_diagram_primer.pdf

**Comment by ErikaWarnatzsch** [comment]
thank you
