### ISSUE TITLE
Missing "Taylor Diagram Primer" PDF document  on new site

### ISSUE THREAD

**Issue by kaabre** [PCMDI/pcmdi.github.io#213]
According to a google search this existed on the old website but I cannot find it on the new one.

**Comment by James-Crean** [comment]
Here is a direct link to it: https://pcmdi.llnl.gov/staff/taylor/CV/Taylor_diagram_primer.pdf?id=25

Would you be able to share the google search and/or links you expected to find it at? I would like to make sure others will be able to locate it right away in the future.

Thanks!

**Comment by kaabre** [comment]
Thanks for the new link and the quick response!

It was actually a duckduckgo search for "How to read taylor diagrams" (not sure it matters what the search engine was), and broken links to the old primer (http://www-pcmdi.llnl.gov/about/staff/Taylor/CV/Taylor_diagram_primer.htm) also appear at https://climatedataguide.ucar.edu/climate-data-tools-and-analysis/taylor-diagrams
