### ISSUE TITLE
Mobile CSS needs work

### ISSUE THREAD

**Issue by durack1** [PCMDI/pcmdi.github.io#241]
@mauzey1 I'm unsure if this change occurred with the recent tweak of the google search box, but it seems that we have a problem on mobile.

On an iPhone XS Max (Problems, more with portrait than landscape):
![img_0171](https://user-images.githubusercontent.com/3229632/51005521-016ce400-14f4-11e9-9153-aa632bd39684.PNG)
![img_0174](https://user-images.githubusercontent.com/3229632/51005524-05006b00-14f4-11e9-8e64-2297bfaa981a.PNG)

On and iPad Air 2 (OK):
![img_0280](https://user-images.githubusercontent.com/3229632/51005528-09c51f00-14f4-11e9-85e6-b6404b8635f3.PNG)
![img_0281](https://user-images.githubusercontent.com/3229632/51005532-0d58a600-14f4-11e9-8df5-09fb695f02c4.PNG)

**Comment by durack1** [comment]
@mauzey1 it seems this is only an issue with the table page, see below
![img_0175](https://user-images.githubusercontent.com/3229632/51010066-7b5a9880-1507-11e9-9df1-24e3b4b03544.PNG)

Ping @taylor13 @sashakames - can you guys both reproduce the problem [above](https://github.com/PCMDI/pcmdi.github.io/issues/241#issue-398076131) (top image)

**Comment by taylor13** [comment]
What problem are you talking about?  Can you explain what you mean by "CSS needs Work"?  What kind of work?  Do you want the PCMDI header to extend to the right side?  Any other issues?  I'll check my phone once I know what to look for.

**Comment by sashakames** [comment]
I don't observe a problem on my 7 plus phone. But I'm not sure if there's missing desired behavior we want.

**Comment by mauzey1** [comment]
This might be due to the tables being too wide.  I will try wrapping the tables in `<div style="overflow-x:auto"> ... </div>` to see if that improves it.  It will make the tables scroll horizontally on smaller screens.

**Comment by durack1** [comment]
@mauzey1 this is fixed for me, so will close
