### ISSUE TITLE
Data Managers Guide

### ISSUE THREAD

**Issue by sashakames** [PCMDI/pcmdi.github.io#253]
We finally have the content needed to complete this page:

https://github.com/PCMDI/pcmdi.github.io/blob/master/CMIP6/Guide/dataManagers.md

The content we want is in this google doc (many links):  https://docs.google.com/document/d/1y6Nd0Bea6VC6iTguFwHZr2uMM56VSpaqaXtQxCX5t-U/edit#heading=h.4m1g9kgsjr9s 

Leave off authors/reviewers

**Comment by mauzey1** [comment]
@sashakames 

Here is the data managers guide with the document's content.
https://github.com/mauzey1/pcmdi.github.io/blob/ebe36253fc55c56bf0950e8cc7df11ce00b4a1b1/CMIP6/Guide/dataManagers.md

There are 3 links in that document that link back to itself.  The links are from the following items:

- (Mandatory) Follow errata workflow
- (Mandatory) Create an errata explaining the reason of this new version
- Follow publication workflow a usual

There is also a typo in that last item.  Will more be added to the Google document?

**Comment by sashakames** [comment]
@mauzey1 Looks great!  

The circular links were meant to reference the numbered items.  Can you link to an anchor in Markdown?  
13.1 and 14.1 would link back to section 12
14.5 would link back to 10 

Also 1 and 6, as those howto text were meant to have links, we can simply remove.

Going forward, others can fork the repo and issue PR to add content / suggest changes
