### ISSUE TITLE
embed CMIP6 institution_id map in CMIP6 guide

### ISSUE THREAD

**Issue by durack1** [PCMDI/pcmdi.github.io#263]
@glevava has generated a great google map page which lists all the CMIP6 contributing institution_id's, see [here](https://www.google.com/maps/d/u/0/viewer?hl=en&ll=20.800709040117336%2C19.91167870000004&z=3&mid=1LG_xEyEA-jlQIO7_Y5_3mGgMwK_8gqXU)

The iframe code below should be embedded into our CMIP6 guide page:
```
<iframe src="https://www.google.com/maps/d/embed?mid=1LG_xEyEA-jlQIO7_Y5_3mGgMwK_8gqXU&hl=en" width="640" height="480"></iframe>
```

@mauzey1 @taylor13 @sashakames

**Comment by durack1** [comment]
@glevava ping

**Comment by durack1** [comment]
@taylor13, @mauzey1 has already implemented an embed of the CMIP6 institution_id map - his PR #264 drops this at https://pcmdi.llnl.gov/CMIP6/Guide/ - but I am not sure this is the right place to put it?

@sashakames do you have any strong feelings about this?

**Comment by mauzey1** [comment]
@durack1 Would having the map at the bottom of https://pcmdi.llnl.gov/CMIP6/ be better?

**Comment by durack1** [comment]
Thanks @mauzey1, I'm trying to pin down @taylor13 to discuss this

**Comment by taylor13** [comment]
Since under "flags" in the Map Legend, only 1 institution is associated with a flag, I think we should either

1) hide the "Legend" (or by default not have it show up), or
2) include *all* the institutions in the list

I think we should provide the link to this map on the following pages:

1) each CMIP6 "projects" page (e.g., https://esgf-node.llnl.gov/projects/cmip6/)  I would modify the first sentence on the page to read:  "The Coupled Model Intercomparison Project, which began in 1995 under the auspices of the World Climate Research Programme (WCRP), is now in its sixth phase (CMIP6) and includes participation by more than 40 institutions and consortia worldwide."  [The link would be activated by clicking on "46 institutions and consortia worldwide"]

2) The CMIP6 home page at PCMDI: https://pcmdi.llnl.gov/CMIP6/    I would modify the first sentence on that page to read: "The WCRP Working Group on Coupled Modelling (WGCM) oversees the Coupled Model Intercomparison Project, which is now in its 6th phase and includes participation by more than 40 institutions and consortia worldwide."  [The link would be activated by clicking on "46 institutions and consortia worldwide"]

**Comment by taylor13** [comment]
Also, Paul and I think we should try embedding the map at the bottom of this page (after the main text part): https://pcmdi.llnl.gov/CMIP6/ 
Just above the image, we should have a title:
"CMIP6 Modeling Groups (click on flags to reveal identity)"

**Comment by mauzey1** [comment]
I have moved the map to https://pcmdi.llnl.gov/CMIP6/
![screenshot-2019-2-13 cmip6 homepage 1](https://user-images.githubusercontent.com/42009431/52753597-28fc1400-2fac-11e9-96da-3a0965cc1e00.png)

**Comment by durack1** [comment]
@mauzey1 looks good to me!

**Comment by taylor13** [comment]
@mauzey1   Me too.  Thanks! Let's go live then someone can close this issue.

**Comment by durack1** [comment]
@mauzey1 this looks great, so here's the breakdown across devices:
Laptop browser:
![screenshot_2019-02-14 cmip6 homepage](https://user-images.githubusercontent.com/3229632/52804638-8d18e980-3039-11e9-89ef-1ed0cbb85d34.png)

iPad Air 2 portrait:
![img_0297](https://user-images.githubusercontent.com/3229632/52804750-df5a0a80-3039-11e9-9732-90112251cbf1.PNG)

iPad Air 2 landscape:
![img_0298](https://user-images.githubusercontent.com/3229632/52804760-e54feb80-3039-11e9-8813-16043f48bfdb.PNG)

iPhone XS Max portrait:
![img_0499](https://user-images.githubusercontent.com/3229632/52804771-eb45cc80-3039-11e9-86a1-301bd193d310.PNG)

iPhone XS Max landscape:
![img_0500](https://user-images.githubusercontent.com/3229632/52804778-f00a8080-3039-11e9-81f0-0489590f2a8b.PNG)

These all look fine to me (it would be nice to think about customizing the site experience dependent on the device), so I think we can close out this issue - closing

**Comment by durack1** [comment]
This map is now updated following the thread below, we should update out pointer to this revised map
```
From: Guillaume LEVAVASSEUR
Date: Wednesday, February 20, 2019 at 8:51 AM
To: "Taylor, Karl E."
Cc: "Durack, Paul J.", "Ames, Sasha", DENVIL Sébastien
Subject: Re: CMIP6 institution map

Hi Karl, Paul and Sasha, 

I think I reach something good now with ESGF map. 

The new map is here : https://goo.gl/HoZ7BE

I recommend to use it on the CMIP6 pages.

What's new :

- I reviewed all the institutions coordinates as some of them were previously wrong due to bad geocoding results.
- I completed the institutions information (homepages, full names, etc.) especially regarding the different CMIP consortiums.
- Each pin ballon includes the institution ID, full name and link to the corresponding homepage. 
- The legend has been sorted alphabetically using institution ID.
- I organized the map into 3 layers : ESGF index nodes, ESGF data nodes and CMIP6 contribution.
- Each layer can be displayed independently.

What I didn't succeed to improve :

- Reduce icon overlaying is difficult. It requires some development to slightly move each pin depending on its neighbours. Consequently, I put lon/lat coordinates as much precise as possible to benefit of the zoom function.
- Some KML icon style properties aren't supported by Google My Maps that's why I choose to divided the placemarks into 3 layers to make it more readable.
- I wanted to display pin labels automatically but some KML label style properties aren't supported too by Google My Maps : /
- KML import cannot be automatic.

You will find the procedure to re-generate the KML file here :
https://github.com/ESGF/esgf-map

To update the map, we just need to update the pyessv-archive first using the two JSON files: 
https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/CMIP6_institution_id.json
https://github.com/ESGF/esgf-map/blob/master/esgf_partners.json

Feel free to ask me if you want I modify some things on the map.

Cheers,

Guillaume
```
@glevava @taylor13 @sashakames @mauzey1 @SebastienDenvil

**Comment by durack1** [comment]
@glevava can I just confirm that the linked map above is not the CMIP6 institution_id entries, but rather the data nodes? And therefore my statement below is incorrect - we leave the institution_id pages as they are (https://pcmdi.llnl.gov/CMIP6/) and rather use the link above https://github.com/PCMDI/pcmdi.github.io/issues/263#issuecomment-468038192 as ESGF node map?

If yes, then I will close this issue and open a new issue that reflects this information correctly

**Comment by durack1** [comment]
Closing this issue

**Comment by durack1** [comment]
@glevava has updated this map which can now be linked at https://www.google.com/maps/d/u/0/embed?mid=1qgItlbd11j6wzirf6vo2Zq_uYqaP4baQ.

@mauzey1 can you please update the link to point to this new URL?

@taylor13 ping
