### ISSUE TITLE
stale IPCC link

### ISSUE THREAD

**Issue by taylor13** [PCMDI/pcmdi.github.io#280]
got this email today.  Haven't confirmed authenticity.  
Dear Dr Karl Taylor,
I hope this email finds you well.

It has come to my attention that your website contains a link to an ipcc pdf about climate change that has become erroneous. This link no longer works as the website no longer exists meaning the relevant information is no longer apparent as it was before. I have seen insight data and am now aware that your website was included in the list of referrers.

As a matter of urgency, I would like to request that you update this link as soon as possible.

The link on your website is situated on  
https://pcmdi.llnl.gov/ipcc/diagnostic_subprojects.html  
under the anchor text " Full Article (the physical science basis. in press)  "

The link that should replace this is:
https://theswitch.co.uk/sites/theswitch.co.uk/files/pdf/SPM2feb07.pdf

Please let me know when this has been completed. A member of our team will be making a follow-up call to ensure that it is handled effectively and efficiently.

Thank you for your collaboration, and have a great day.
Kind Regards
Carly Thorpe

**Comment by durack1** [comment]
@taylor13 what is the domain that Carly is sending from? @XXX.YYY?

**Comment by taylor13** [comment]
carly.thorpe@selectra.co.uk

**Comment by durack1** [comment]
Not sure this is a valid request - theswitch appears to be a private website

**Comment by mauzey1** [comment]
I'm guessing they were referring to this article from https://pcmdi.llnl.gov/ipcc/diagnostic_subprojects.html.

> Alley, R., et alii, 2007: Summary for Policymakers. Climate Change 2007: The Physical Science Basis. In press. Full Article.

Would this be the article?
https://www.ipcc.ch/site/assets/uploads/2018/02/ar4-wg1-spm-1.pdf

**Comment by durack1** [comment]
@mauzey1 I think you're right, we also need to correct the `et alii -> et al.`
