### ISSUE TITLE
Can't find the link: http://pypi.python.org/simple/esgf-dashboard/

### ISSUE THREAD

**Issue by jackask** [PCMDI/pcmdi.github.io#283]
when seting up the ESGF-NODE, the following link can't be find:
 http://pypi.python.org/simple/esgf-dashboard/

Could you please tell us how the problem be solved?  Thanks so much!

**Comment by taylor13** [comment]
@sashakames I suspect this link might be in the guidance doc for data managers, https://pcmdi.llnl.gov/CMIP6/Guide/dataManagers.html, but I can't find it.

@jackask could you please help by telling us where you encountered the above link?

**Comment by taylor13** [comment]
@jackask could you please help by telling us where you encountered the above link?

**Comment by mauzey1** [comment]
@sashakames Should there be installation instructions for esgf-dashboard?  I didn't see any on https://pcmdi.llnl.gov/CMIP6/Guide/dataManagers.html.  PyPI didn't have esgf-dashboard.

**Comment by sashakames** [comment]
Duplicate issue (saw this on esgf-installer.
