### ISSUE TITLE
Missing IM numbers for MSU data

### ISSUE THREAD

**Issue by mauzey1** [PCMDI/pcmdi.github.io#295]
@durack1 @taylor13 @gleckler1
There are missing IM numbers for [Causes of differences in model in satellite tropospheric warming rates](https://pcmdi.llnl.gov/research/DandA/Synthetic%20Microwave%20Sounding%20Unit%20(MSU)%20temperatures/2017/Nature_Geoscience/index.html) and [Human influence on the seasonal cycle of tropospheric temperature](https://pcmdi.llnl.gov/research/DandA/Synthetic%20Microwave%20Sounding%20Unit%20(MSU)%20temperatures/2018/index.html)

**Comment by durack1** [comment]
@mauzey1 thanks for raising this. The pages are the D&A activity, which is led by Ben (Santer), so it would be useful to direct this query to Ben. I’m not certain if @mattben hadn’t already started the IM process?

**Comment by durack1** [comment]
@pochedls do you have any knowledge of the status of this request? I presume these datasets should remain available on the page?

**Comment by pochedls** [comment]
I think they all should fall under: [LLNL-IM-729103](https://pcmdi.llnl.gov/research/DandA/Synthetic%20Microwave%20Sounding%20Unit%20(MSU)%20temperatures/2017/Scientific_Reports/index.html).

**Comment by durack1** [comment]
@pochedls champ, thanks for this!
