### ISSUE TITLE
Site transfer

### ISSUE THREAD

**Issue by mattben** [PCMDI/pcmdi.github.io#3]
webshooter won't work, this site is too large.

we are hand copying important pages from http://www-pcmdi.llnl.gov to http://pcmdi.github.io

Paul is your point of contact. 

you have freedom to make each page suck less by chaining layout and reducing un-needed content.

**Comment by doutriaux1** [comment]
mips are missing. publication list seems stuck in 2013.

**Comment by mattben** [comment]
work well in to process
