### ISSUE TITLE
PCMDI report 18 not available

### ISSUE THREAD

**Issue by durack1** [PCMDI/pcmdi.github.io#301]
The URL https://pcmdi.llnl.gov/report/pdf/rep18.pdf?id=7 linked off https://pcmdi.llnl.gov/report/report.html points to a non-existent pdf. If the pdf can be found in archives and reinstated that would be great

@taylor13 ping

**Comment by mauzey1** [comment]
@durack1 I can't find that URL anywhere on the site.  Did you mean https://pcmdi.llnl.gov/report/pdf/18.pdf?id=85 found on https://pcmdi.llnl.gov/report/ab18.html?  Looking through the commit history, it looks like no such file was uploaded.  Here's when the reports were uploaded: https://github.com/PCMDI/pcmdi.github.io/commit/4711487361f7f5906701431fb88261e0e6e44bc3

**Comment by durack1** [comment]
@mauzey1 thanks for looking at this. I wonder if someone, maybe @taylor13 has a digital copy of this somewhere? Failing that maybe we have a copy of the file in a backup somewhere, @hoang1 might know..?

**Comment by hoang1** [comment]
Hi Paul, Chris,

I need a bit more detail regarding the missing file/report before I can look up in the backup……………..Tony

**Comment by durack1** [comment]
Thanks @hoang1, the missing file might be called `18.pdf`, it's the report by Tom Phillips titled "A Summary Documentation of the AMIP Models" and linked off https://pcmdi.llnl.gov/report/ab18.html

In addition to this missing file, there may also be others.

**Comment by durack1** [comment]
@mauzey1 @hoang1 it appears there might be a pdf at https://www.researchgate.net/publication/228701808_A_summary_documentation_of_the_AMIP_models.

Another link https://digital.library.unt.edu/ark:/67531/metadc665953/m2/1/high_res_d/26547.pdf appears to be very slowly loading
