### ISSUE TITLE
broken link to CMIP5 branch times

### ISSUE THREAD

**Issue by shortda** [PCMDI/pcmdi.github.io#317]
The CMIP5 Data Issues page (https://pcmdi.llnl.gov/mips/cmip5/errata.html) has a link to a table that should contain corrected branch times for CMIP5 model output, but the link is broken. The entry is dated 8 February 2012 and the broken link is http://pcmdi-cmip.llnl.gov/cmip5/errata/jgregory_cmip5ancestry.txt

A 2017 paper (DOI 10.1007/s00382-017-3867-7) contains a published reference to that URL and there are a few other links floating around online, so I'd appreciate it if someone could set up a redirect to the table. As far as I know there is currently no publicly available source for that information.

**Comment by durack1** [comment]
@shortda can you drop the most up-to-date file here in this issue so we're not only fixing the dead link but also providing the most up-to-date info

**Comment by shortda** [comment]
I was waiting on permission from Jonathan Gregory to send this on. I've attached his latest version of the CMIP5 branching times. Columns are:

model | child run | child rip | branch year in child coordinates | parent run | parent rip | branch year in parent coordinates | status

An equals sign in the parent year means it's the same value as in the child year. Status OK means Jonathan checked for time series continuity.

[cmip5_ancestry.txt](https://github.com/PCMDI/pcmdi.github.io/files/3628536/cmip5_ancestry.txt)

**Comment by mauzey1** [comment]
@shortda @durack1 I have updated jgregory_cmip5ancestry.txt with the data in the new file.

**Comment by shortda** [comment]
The link I see from the Data Issues page has changed - it's now https://pcmdi.llnl.gov/mips/cmip5/jgregory_cmip5ancestry.txt - but I get a 404 error when I click on it

**Comment by mauzey1** [comment]
@shortda When #318 gets approved and merged, then the file will be available on the server.

**Comment by shortda** [comment]
got it, sorry
