### ISSUE TITLE
Wrong CMIP6 menu entry for Guides

### ISSUE THREAD

**Issue by MartinaSt** [PCMDI/pcmdi.github.io#337]
@durack1 : The CMIP6 menu entry on the PCMDI web page includes a link to the Data Users Guide (https://pcmdi.llnl.gov/CMIP6/Guide/dataUsers.html ) instead of a link to the general guidance page "Guide to CMIP6 Participation" (https://pcmdi.llnl.gov/CMIP6/Guide/)

**Comment by MartinaSt** [comment]
Sorry, the general Guide is there. It is an inconsistency for the specific guides. Either the other two Guides for modeling centers and data node managers are missing or the data guide is to be excluded.

**Comment by durack1** [comment]
@MartinaSt apologies for the slow uptake, we've had a site outage this week so this dropped off the immediate priority.

Are you suggesting that we add entries to the drop down menus for CMIP6?

We currently have:
```
<li><a href="/CMIP6/">Overview</a></li>
<li><a href="/CMIP6/Guide/dataUsers.html">Data Users Guide</a></li>
<li><a href="/CMIP6/ArchiveStatistics/esgf_data_holdings/">Current Data Holdings</a></li>
<li><a href="http://esgf-node.llnl.gov/search/cmip6">CMIP6 Data Search</a></li>
```

What are you proposing?

**Comment by MartinaSt** [comment]
Thanks @durack1 for making this a priority. 

I'd prefer to have all three Guides in the menu. I thought I saw that in the past but I am not sure. 

The other consistent alternative would be to replace the link to the Data Users Guide to the link to all Guides (https://pcmdi.llnl.gov/CMIP6/Guide/). I am fine with both.
