### ISSUE TITLE
Staff list needs to be updated

### ISSUE THREAD

**Issue by lee1043** [PCMDI/pcmdi.github.io#360]
Staff list at https://pcmdi.llnl.gov/staff/ needs to be updated to current.

**Comment by durack1** [comment]
@lee1043 you can submit a PR to https://github.com/PCMDI/pcmdi.github.io/blob/master/staff/index.md

**Comment by lee1043** [comment]
@durack1 I understand for the technical sense, but I think I was looking for more of strategical decision with help from admin for the up-to-date list. @gleckler1 @taylor13 any advice?

**Comment by durack1** [comment]
@lee1043 very good question. I suppose we need to remove Ken, Charles, Matt, Denis, Dean add Min-Seop, note Curt and Tom are retired/honorary

Happy for @gleckler1 and @taylor13 to provide some insights

**Comment by lee1043** [comment]
I think we also need to add others such as Mark, Hsi-Yen, Steve P, and so on.

**Comment by lee1043** [comment]
And we may want to not include email and phone number in the [list page](https://pcmdi.llnl.gov/staff/) while it can still be found from the individual's page, in effort to not give easy picking list to spammers.

**Comment by lee1043** [comment]
My proposal for the format of staff list page: https://lee1043.github.io/staff/
Email addresses and phone numbers were hidden from the list but still can be found from individuals' pages.

**Comment by lee1043** [comment]
new branch: https://github.com/PCMDI/pcmdi.github.io/tree/staff_update

**Comment by lee1043** [comment]
https://github.com/PCMDI/pcmdi.github.io/blob/staff_update/staff/index.md
My proposal is to hide email addresses and phone numbers from the list page but still can be found from individuals' pages.

**Comment by durack1** [comment]
If your concern is bots scraping addresses, if they exist on one place, linked they’re already scraped so not a compelling reason to change the format. In addition our email is heavily scrubbed with much spam already caught

**Comment by lee1043** [comment]
@durack1 you have a point... I am bringing emails and phone numbers back.

**Comment by durack1** [comment]
@lee1043 if you wanted to systematically fix those issues see what I have done on https://pcmdi.llnl.gov/staff/durack/index.html, it’s not perfect, but would solve some of the direct bot scrape issues. Having said that, I didn’t stomp out the other complete email addresses on the master page, oh well

**Comment by durack1** [comment]
@lee1043 are you happy for this to be closed? https://pcmdi.llnl.gov/staff/ looks updated to me

**Comment by lee1043** [comment]
@durack1 yes, thanks for housekeeping work.
