### ISSUE TITLE
Missing activities on the CMIP6 data holdings page

### ISSUE THREAD

**Issue by durack1** [PCMDI/pcmdi.github.io#385]
It seems that previously published datasets are now missing on the [ESGF CMIP6 Data Holdings page](https://pcmdi.llnl.gov/CMIP6/ArchiveStatistics/esgf_data_holdings/print_view.html), in particular data for the ISMIP6 activity for the models:
```python
-bash-4.2$ ls ../CMIP6/ISMIP6/*/
..CMIP6/ISMIP6/NASA-GISS/:
GISS-E2-1-G

../CMIP6/ISMIP6/NCAR/:
CESM2
```

I'm guessing this may just be the tip of the iceberg, and may be related to the index shards standing issue

@mauzey1 @sashakames @nathanlcarlson @taylor13

**Comment by taylor13** [comment]
If Paul is correct about this, it deserves some immediate attention.  Any way I can help?

**Comment by durack1** [comment]
I note that these data are also missing on the ESGF search https://esgf-node.llnl.gov/search/cmip6/?activity_id=ISMIP6

**Comment by durack1** [comment]
Oh dear, it seems the problem is escalating
![Screenshot_2020-08-19 cmip6 Data Search cmip6 ESGF-CoG](https://user-images.githubusercontent.com/3229632/90677337-15b9ac80-e212-11ea-8349-6d01150bf301.png)

**Comment by taylor13** [comment]
I note that if you Show all Versions and Show All Replicas you get 65 datasets, but most have been retracted.  If you "Show all Replicas" you get 4 datasets.  Not sure what this means.

**Comment by mauzey1** [comment]
The ESGF CMIP6 data holdings page directly queries the Solr database used by ESGF search, so any issues that are affecting Solr will cause issues for the data holdings page.

Currently, the search results for ISMIP6 have been erratic.  I'm not sure what is happening with Solr.

@nathanlcarlson @sashakames Do you have any insight on what could be happening?

**Comment by durack1** [comment]
It's a shard problem again

https://esgf-data.dkrz.de/search/cmip6-dkrz/?activity_id=ISMIP6 vs
https://esgf-node.ipsl.upmc.fr/search/cmip6-ipsl/?activity_id=ISMIP6 vs
https://esgf-node.llnl.gov/search/cmip6/?activity_id=ISMIP6

It looks like ISMIP6 is back on LLNL node

**Comment by durack1** [comment]
@mauzey1 [ISMIP6](https://pcmdi.llnl.gov/CMIP6/ArchiveStatistics/esgf_data_holdings/ISMIP6/index.html) now shows up on the holdings page, so will close this
