### ISSUE TITLE
Updated CMIP5 list of modeling groups

### ISSUE THREAD

**Issue by taylor13** [PCMDI/pcmdi.github.io#389]
@mauzey1   Is it possible that those users seeking access to https://pcmdi.llnl.gov/mips/cmip5/docs/CMIP5_modeling_groups.pdf?id=37 or https://pcmdi.llnl.gov/mips/cmip5/docs/CMIP5_modeling_groups.docx  could be redirected to the updated document at  https://pcmdi.llnl.gov/mips/cmip5/availability.html ?    If not, what other options are there?  We could, I suppose, just remove the references to them on https://pcmdi.llnl.gov/mips/cmip5/terms-of-use.html and on https://pcmdi.llnl.gov/mips/cmip5/usefulDocuments.html, but then any external references to this information would be broken

thanks.

**Comment by mauzey1** [comment]
@taylor13 We can change/remove the links on those pages without breaking external references to those files.  As long as the files are still hosted on the site, anyone with their links can still access them.  Or were you planning to have those documents deleted instead?

**Comment by taylor13** [comment]
We should delete those documents because they are now out-of-date, and I don't think we should burden ourselves with keeping them up-to-date, when we can simply point to the page that we plan to maintain indefinitely: https://pcmdi.llnl.gov/mips/cmip5/availability.html
