### ISSUE TITLE
broken CMIP5 links

### ISSUE THREAD

**Issue by taylor13** [PCMDI/pcmdi.github.io#390]
@martinjuckes noted:
```
we've noticed a few broken links in the CMIP5 license conditions which we use for 
people accessing the data locally at CEDA. These are copied from https://pcmdi.llnl.gov
/mips/cmip5/terms-of-use.html .. and there are broken links in there (links to 
https://pcmdi.llnl.gov/cmip5/.. which should be https://pcmdi.llnl.gov/mips/cmip5/.. ). 
The page also gives Dean's email as a contact ... should we replace this with Paul's 
address?  
```
I agree we should fix these problems and replace Dean with Paul (@durack1)

**Comment by sashakames** [comment]
I just saw this @taylor13 , should we assign @mauzey1 ?

**Comment by taylor13** [comment]
Yes please.

**Comment by lee1043** [comment]
This PR seems taken care of, so closing this issue.

**Comment by durack1** [comment]
@lee1043 23 probably need to triple check that all instances of williamsXX@ (global repo search) are replaced with a valid email, mine would do

**Comment by durack1** [comment]
It looks like there [are still some instances](https://github.com/PCMDI/pcmdi.github.io/search?q=williams13), but each page is a ~decade old and so can remain as archival.

Leaving this closed
