### ISSUE TITLE
cannot access http://www-pcmdi.llnl.gov/amip2/AMIP2EXPDSN/BCS/amip2bcs.html 

### ISSUE THREAD

**Issue by daye222** [PCMDI/pcmdi.github.io#399]
where can I get AMIP II BCS data(SST and Ice)?
I cannot access I cannot access http://www-pcmdi.llnl.gov/amip2/AMIP2EXPDSN/BCS/amip2bcs.html.
where can I go?

**Comment by taylor13** [comment]
This data is now hosted here: https://esgf-node.llnl.gov/projects/input4mips/
