### ISSUE TITLE
Updating CMIP5 terms of use

### ISSUE THREAD

**Issue by durack1** [PCMDI/pcmdi.github.io#421]
The information about CMIP5 data usage is now outdated on the site and needs a refresh with details contained in an email from May 2020 below:

From: "Taylor, Karl E."
Date: Thursday, May 21, 2020 at 12:11 PM
Subject: Re: [Re-send] Quick question: Redistribution of modified [unclassified]

Dear Akiko,

I’m sorry for the slow response. All the CMIP5 data is now available for unrestricted use and some of the guidance provided at  
https://pcmdi.llnl.gov/mips/cmip5/terms-of-use.html Is now outdated, so please follow the “Terms of Use” guidance found at https://pcmdi.llnl.gov/CMIP6/TermsOfUse/TermsOfUse6-1.html.  

I am copying members and ex-members of the WCRP committees who oversee CMIP to see if  they are comfortable with the following policy:

You may redistribute data, but please make sure folks that use your “derived data product” are aware of the CMIP6 Terms of Use and that 
1)	CMIP5 data is available for unrestricted use, and
2)	CMIP6 data is governed by the license provided in the header of each data file (and which may differ from one model to the next).  

I would think that your derived data product would be governed by the same licensing restrictions as the original CMIP6 data.

It is essential that your website make clear that the data you plan to distribute is *not* the data that the climate models produced, but has been modified in a way that has not been necessarily approved by the modeling centers (and clearly does not represent the climate actually simulated by the models).  I think your users would appreciate it if you provided prominent links to the main CMIP6 sites (https://pcmdi.llnl.gov/CMIP6 and https://www.wcrp-climate.org/wgcm-cmip/wgcm-cmip6 ) and CMIP5 sites (https://pcmdi.llnl.gov/mips/cmip5/ and https://www.wcrp-climate.org/wgcm-cmip/wgcm-cmip5  ) so they could get additional information about the original data (or download the original data itself). You could also point them to the CMIP6 terms of use document: https://pcmdi.llnl.gov/CMIP6/TermsOfUse/TermsOfUse6-1.html .

Thanks and best regards,
Karl

@taylor13 @matthew-mizielinski ping

**Comment by durack1** [comment]
And this was the query that prompted the above

From: Taylor, Karl E.
Sent: 21 September 2021 23:04
To: Durack, Paul J.; Mizielinski, Matthew
Subject: FW: Permission to share form for CMIP5 outputs
 
This email was received from an external source.   Always check sender details, links & attachments.

Hi Paul and Matt,
 
I received this request today.  CMIP5 output is now available now without restriction, so the request below is unnecessary.  Unless I hear any objection from you, I’ll let Heloise know.  We should also probably update https://pcmdi.llnl.gov/mips/cmip5/terms-of-use.html  (and eliminate reference to the “permission_to_share_form.docx”.
 
Karl
 
From: Heloise Michaud
Date: Tuesday, September 21, 2021 at 5:41 AM
To: "Taylor, Karl E."
Cc: Leo Seyfried
Subject: Permission to share form for CMIP5 outputs
 
Hello,
 
Please find enclosed the permission to share file for me and my collegue Léo Seyfried.
Best Regards,
 
Héloïse Michaud
 
 
--
Héloïse MICHAUD
Expert en Etats de mer
Shom Antenne de Toulouse
BP xx017 - 31032 Toulouse CEDEX 5
Tél. 06 87 96 xx (pdt le confinement)

**Comment by durack1** [comment]
The plan now is to update the existing page with new contents (google doc link https://github.com/PCMDI/pcmdi.github.io/issues/421#issuecomment-925186186) and then archive the old version - with a link on the new page.

I will update the existing PR #422 and remove the draft tag when this is done

**Comment by durack1** [comment]
Ok great, the updated terms of use are now live at https://pcmdi.llnl.gov/mips/cmip5/terms-of-use.html

**Comment by taylor13** [comment]
Looks good to me.  Thanks Paul and Chris.
