### ISSUE TITLE
Add navigation links to ESGF CMIP6 Data Holdings pages

### ISSUE THREAD

**Issue by durack1** [PCMDI/pcmdi.github.io#425]
It'd be great to add another nav link, so that when you get to the MIP subpages (of the ESGF CMIP6 Data Holdings pages) you can navigate back to the home page, so changing the pages from this
![220107_2053-GeoMIP](https://user-images.githubusercontent.com/3229632/148632079-888ccf73-52e8-4187-8183-c14398c28bf9.png)

to this (i.e. add "ESGF Data Holdings Home" link next to print link)
![220107_2051-GeoMIP-UpdatedNav](https://user-images.githubusercontent.com/3229632/148632081-eefa0f58-d7c8-48a6-9396-ac05ad1cc847.png)

**Comment by mauzey1** [comment]
@durack1 
I have added this change as well as added a link in the "print friendly" pages that will bring you back to the site-formatted page.
![Screenshot 2022-01-10 at 16-23-29 ESGF CMIP6 CFMIP Data Holdings](https://user-images.githubusercontent.com/42009431/148860033-c33ef771-0852-4247-9a0d-39eeb44d4617.png)

**Comment by durack1** [comment]
@mauzey1 absolute hero! Look forward to seeing them live
