### ISSUE TITLE
Add google analytics tracking block

### ISSUE THREAD

**Issue by durack1** [PCMDI/pcmdi.github.io#431]
@mauzey1 can we add some Google Analytics tracking code to our standard footer (while #429 is underway)?

An example can be found in {{site.baseurl}}/staff/durack/googleAnalyticsTag.js with the code block:
```
<!-- Global site tag (gtag.js) - Google Analytics -->
<script type="text/javascript" src="googleAnalyticsTag.js" ></script>
```

**Comment by durack1** [comment]
@mauzey1 this was that google analytics tag that I was hoping we could also add to the footer compliance update (#429)

**Comment by mauzey1** [comment]
@durack1 Would you mind if we moved that script from your staff directory to the Data/media/js directory?

**Comment by durack1** [comment]
@mauzey1 that's fine, if you're happy to just copy, so that if I need to tweak the info for my staff page I can do that independently
