### ISSUE TITLE
Update homepage graphic

### ISSUE THREAD

**Issue by durack1** [PCMDI/pcmdi.github.io#438]
@mauzey1 attached are two versions of a home page replacement graphic, *.svg and *.png (which I assumed required 940px width). Adding these to this repo, so you have them available in a PR

**Comment by durack1** [comment]
@mauzey1 one of the things that @klein21 and I talked about, was updating the homepage so that we satisfy the (future) requirements, including alt text and other access tags for all graphic objects to ensure that vision impaired folks can also navigate the site.

Is there a short list of what is required for the homepage? If you require input text, I am happy to provide this as we revise the graphic(s)

**Comment by mauzey1** [comment]
@durack1 Is there a specific alt text for the PCMDI logo that you want?  Can it just be "PCMDI logo"?

**Comment by durack1** [comment]
@mauzey1 we have 4 graphics on the page (or will do when the banner box is replaced). I suggest:

new PCMDI logo:
"PCMDI Earth System Model Evaluation Project - logo"
existing DOE logo:
"US Department of Energy - logo"
existing (blue) LLNL logo:
"Lawrence Livermore National Laboratory - logo"
existing NNSA, DOE, LLNS LLC:
"National Nuclear Security Administration - logo"
"US Department of Energy - logo"
"Lawrence Livermore National Security, LLC - logo"

Curiously, I took a peek at all of these other sites, and they aren't providing alt text either, we may be waaay ahead of the curve
