### ISSUE TITLE
Update staff page

### ISSUE THREAD

**Issue by durack1** [PCMDI/pcmdi.github.io#445]
In discussions with @klein21 we've considered having an expanded list of active, collaborators and former project participants. This issue will capture discussions on this topic

**Comment by klein21** [comment]
Here's my ideas for this.  There should be 3 categories and here's my suggested terminology and definitions:

1. Core Staff:   People who are currently funded by the project.   Core staff include people both at LLNL and not at LLNL.

2. Affiliated Contributors:   People who are not funded by the project currently, but are making contributions to the project.

3. Former Participants: People who are: (1) not funded currently, (2) were previously funded as Core staff, and (3) are not making any active contributions to the project.

**Comment by durack1** [comment]
@klein21 that first pass is missing:
- [ ] - postdocs (UColorado, UCLA, Princeton)
- [ ] - funded external staff (UColorado, UCLA)
- [ ] - other collaborators (PMP contributors, CMEC contributors, ...)

**Comment by klein21** [comment]
@durack1 

I had envisioned that the currently funded postdocs, research staff, and faculty at Colorado State University, UCLA, and Princeton would be listed under "Core Staff".   That way, the term "Core Staff" includes anyone who is currently getting their salary paid (either in full or partially) from the PCMDI SFA budget. 

As for PMP or CMEC contributors, I would list them under "Affiliated Contributors".

**Comment by durack1** [comment]
@klein21 next on the to-do list is likely https://pcmdi.llnl.gov/about.html - as this is now inconsistent with the staff page

**Comment by klein21** [comment]
@durack1 

I was thinking of tackling the research highlights page (https://pcmdi.github.io/research/researchHighlights.html) next.  But I also was aware of this page. 

Is the about page even needed?   It seems redundant with the content on the main page.  

As for the staff listing, why is this needed on this page?   I would remove the staff listing as a first thing of editing this page, if we still want to keep it.

**Comment by durack1** [comment]
@klein21 agreed mostly, the information on the about page does duplicate the homepage somewhat, so yes, purging this to simplify things might be the easiest path forward

**Comment by klein21** [comment]
@durack1 

Also I wonder if we really need the "Location" page under the "About" tab.

My idea is to get rid of the the Overview and Location pages, and then a level of drop down menu can be removed and the "About" can just be replaced with "People" or "Staff" and take one directly to the Staff page.   What would you think about that?

**Comment by lee1043** [comment]
I think this issue can be closed now.
