### ISSUE TITLE
CMIP guide/CMIP6 license updates

### ISSUE THREAD

**Issue by taylor13** [PCMDI/pcmdi.github.io#464]
The following links are broken on both [Accessing model output](https://pcmdi.llnl.gov/CMIP6/Guide/dataUsers.html#3-accessing-model-output) and [Model output requirements](https://pcmdi.llnl.gov/CMIP6/Guide/modelers.html#5-model-output-requirements):

- [Information on pressure levels](https://www.earthsystemcog.org/site_media/projects/wip/CMIP6_pressure_levels.pdf?id=86)
- [Guidance on time-averaging](https://www.earthsystemcog.org/projects/wip/time_averages)

The first link should be to: https://cmip6dr.github.io/Data_Request_Home/Documents/CMIP6_pressure_levels.pdf 

I don't know where the second document is.

**Comment by mauzey1** [comment]
@taylor13 

The domain http://www.earthsystemcog.org/ is now redirecting to [legacy-escog.github.io](https://github.com/legacy-escog/legacy-escog.github.io).

There are other earthsystemcog.org links on the [Data Users](https://pcmdi.llnl.gov/CMIP6/Guide/dataUsers.html) and [Modelers](https://pcmdi.llnl.gov/CMIP6/Guide/modelers.html) pages.  These links don't work with HTTPS.  Some links will redirect, such as www.earthsystemcog.org/projects/wip.  However, most are 404.

**Comment by taylor13** [comment]
Sorry, if I should understand, but I'm not sure what you're saying.  Are you saying we can't fix the broken links, or we need to fix more links than the ones I noticed?  Or ???

**Comment by durack1** [comment]
thanks @mauzey1, if we can identify these "dead" links, we can make sure to locate the information they were pointing to, and either reproduce this in our repo (and switch links), or add to the https://github.com/WCRP-CMIP/WGCM_Infrastructure_Panel repo and link to it from there - how many http://www.earthsystemcog.org/ links do we need to correct

Ref https://github.com/WCRP-CMIP/WGCM_Infrastructure_Panel/issues/7
Ref https://github.com/WCRP-CMIP/WGCM_Infrastructure_Panel/issues/2 (I believe this is solved)

**Comment by durack1** [comment]
@taylor13 the **guidance on time averaging** content can be found via the [waybackmachine](https://web.archive.org/web/20201020095856/https://www.earthsystemcog.org/projects/wip/time_averages) - so we have the content we can harvest.

@mauzey1 is the dataUsers.html page we need the following changed:
https://www.earthsystemcog.org/projects/wip/CMIP6DataRequest -> https://cmip6dr.github.io/Data_Request_Home
https://www.earthsystemcog.org/site_media/projects/wip/CMIP6_pressure_levels.pdf -> https://cmip6dr.github.io/Data_Request_Home/Documents/CMIP6_pressure_levels.pdf
https://www.earthsystemcog.org/projects/wip/time_averages -> content found on the [waybackmachine](https://web.archive.org/web/20201020095856/https://www.earthsystemcog.org/projects/wip/time_averages) link above
https://www.earthsystemcog.org/projects/wip -> https://wcrp-cmip.github.io/WGCM_Infrastructure_Panel
https://www.earthsystemcog.org/projects/wip/aboutus/ -> https://wcrp-cmip.github.io/WGCM_Infrastructure_Panel

The additional link on the modelers.html page that needs changing is
https://www.earthsystemcog.org/projects/obs4mips/ -> https://pcmdi.github.io/obs4MIPs/

**Comment by durack1** [comment]
Relabelling this issue to capture a number of changes, including the CMIP6 license updates - https://github.com/orgs/WCRP-CMIP/projects/2

@matthew-mizielinski @taylor13 ping

**Comment by durack1** [comment]
To do's -
Fix www.earthsystemcog.org dead links
- [ ] CMIP6 Guide: Data Users, Modelers pages
- [ ] CMIP6DataRequest
- [ ] CMIP6 pressure levels pdf
- [ ] WIP time averages
- [ ] WIP link (home page and about us)
- [ ] obs4MIPs
CMIP6 licenses updates - HTML rendering to be linked off
- [ ] CMIP6 terms of use
- [ ] CMIP6 guide data users
- [ ] CMIP6 archive statistics
- [ ] WIP
