### ISSUE TITLE
Minor tweaks to website

### ISSUE THREAD

**Issue by paullric** [PCMDI/pcmdi.github.io#491]
Project staff:
-	Add post-doctoral research scientist Bo Dong (state date 4/3/2023)
-	Move Steve Klein to “Former participants”
-	Add Paul Ullrich as Project Leader / remove me under UC Davis

Publications drop-down:
-	Move PCMDI to top of drop-down
-	Change CMIP to CMIP5
-	Add CMIP6 link https://cmip-publications.llnl.gov/view/CMIP6/

Research drop-down:
-	Change Metrics to Evaluation
-	Under Overview change Climate Model Metrics to Climate Model Evaluation

**Comment by paullric** [comment]
Yes on both counts.

~ Paul

**Comment by mauzey1** [comment]
Should Steve Klein still have his position as "Project Leader" or should it be set to "Research Scientist" in the former participants list?

**Comment by paullric** [comment]
Suggest keeping his position as Project Leader.
