### ISSUE TITLE
Staff update

### ISSUE THREAD

**Issue by lee1043** [PCMDI/pcmdi.github.io#501]
Can we move 
- Hongchen to former participant
- Yi to PNNL (@mzelinka can you confirm if she is still on the PCMDI project?)

**Comment by mzelinka** [comment]
Yes, Yi is still part of the PCMDI project.

**Comment by mauzey1** [comment]
@lee1043 Should I remove the contact info for people who no longer work at LLNL?  Hongchen's people page is inaccessible.  If Yi is at PNNL, then are they no longer using their LLNL phone and email?

**Comment by lee1043** [comment]
@mauzey1 yes, please remove lab email and phone number for those no longer at LLNL. I think Yi no longer use LLNL contact info.
