### ISSUE TITLE
broken link for obs4mips

### ISSUE THREAD

**Issue by sashakames** [PCMDI/pcmdi.github.io#517]
On the obs4mips page (I'm tracking down updated pages to link in the Metagrid projects) found the following: https://www.earthsystemcog.org/projects/obs4mips/
The obs4mips site was migrated to LLNL CoG but that will be retired likely before the end of the year, and I recall a new obs4mips site is under development (a gh-pages site?)

**Comment by gleckler1** [comment]
@sashakames  Hi Sasha.   The updated site is: https://pcmdi.github.io/obs4MIPs/

**Comment by sashakames** [comment]
Thanks @gleckler1 we'll use that on Metagrid going forward.
