### ISSUE TITLE
https://pcmdi.llnl.gov/home/ not live

### ISSUE THREAD

**Issue by durack1** [PCMDI/pcmdi.github.io#53]
Hi @pawpepe @mattben it seems that the URL above is still not up-to-date. It'd be great to get this site live ASAP as our program manager has requested that content be updated this week for a meeting she is having

@taylor13 pinging you here

**Comment by mattben** [comment]
@pawpepe 

I just pulled the latest on to the server, it seem the paths are wrong. on the server the site lives at`/home' you need to change the paths. I believe the simple fix it so start links with `/` so `/about.html` not `about.html`

Lets not hard code `/home/` in to all the links as the site may move again.

**Comment by durack1** [comment]
@mattben @pawpepe thanks!

**Comment by mattben** [comment]
I just corrected the cronjob on pcmdi so now every hour on the hour the site will update automatically.

**Comment by durack1** [comment]
@mattben great, that'll help things out a fair bit!
