### ISSUE TITLE
Webpage is not up to date with the github repo

### ISSUE THREAD

**Issue by lee1043** [PCMDI/pcmdi.github.io#536]
https://pcmdi.llnl.gov/research/metrics/

The above page shows v1.6.0 while the recent merges updated it to v1.6.2. It looks like webserver is not up to date with this github repo.

**Comment by mauzey1** [comment]
@lee1043 The server for the site is currently undergoing maintenance.  It should be restored to the latest version once completed.

**Comment by lee1043** [comment]
@mauzey1 I see, thank you for clarification.

**Comment by mauzey1** [comment]
@lee1043 The website has now been restored to the latest version.
