### ISSUE TITLE
change of application url

### ISSUE THREAD

**Issue by mattben** [PCMDI/pcmdi.github.io#58]
On http://cmip-pcmdi.llnl.gov/cmip5/publications.html I've updated the links to the cmip publication page. All references to the CMIP publication site should now point to https://cmip-publications.llnl.gov and for specifically CMIP5 publications https://cmip-publications.llnl.gov/search?type=project&option=CMIP5

**Comment by pawpepe** [comment]
I have updated on the new PCMDI website the equivalent page to [ http://cmip-pcmdi.llnl.gov/cmip5/publications.html]( http://cmip-pcmdi.llnl.gov/cmip5/publications.html) also redirect to the CMIP publication site

**Comment by mattben** [comment]
Did you mean to reopen this issue or just comment on it? all the above links point to the correct site.
