### ISSUE TITLE
Purge redundant files

### ISSUE THREAD

**Issue by durack1** [PCMDI/pcmdi.github.io#72]
@pawpepe there are a couple of files in the directory that need to be purged:

https://github.com/PCMDI/pcmdi.github.io/blob/master/:
https://github.com/PCMDI/pcmdi.github.io/blob/master/%5D%5C
https://github.com/PCMDI/pcmdi.github.io/blob/master/blank.md

**Comment by durack1** [comment]
@mattben happy to do a cleanup here, but I am uncertain of what files/dirs are required for the cronjob/jekyll/etc..

**Comment by durack1** [comment]
@mattben purge https://github.com/PCMDI/pcmdi.github.io/blob/master/README.md?

**Comment by mattben** [comment]
Its common for a repo to have a README file, but I agree this one has no useful information.

**Comment by durack1** [comment]
@mattben the fact that there is a `README.md` AND a `README.markdown` was more my question, looks like `README.markdown` is the one that is presented on the repo homepage

**Comment by mattben** [comment]
agh, agreed, corrected.

**Comment by durack1** [comment]
@mattben `_config.yml`?

**Comment by mattben** [comment]
Those are required files for jekyll when it builds the static web site.

**Comment by durack1** [comment]
@mattben is there any redundancy in the files contained in `_layouts` seems like 9 separate layouts is a lot to manage.. Fewer would make maintenance easier
