### ISSUE TITLE
Live website not updating correctly?

### ISSUE THREAD

**Issue by durack1** [PCMDI/pcmdi.github.io#84]
@mattben it seems that the github hosted http://pcmdi.github.io/staff.html and LLNL hosted https://pcmdi.llnl.gov/home/staff.html pages are not in sync.

Can you please check to see that the cronjob is running correctly?

**Comment by mattben** [comment]
Will do, i've cc'ed you @durack1

**Comment by durack1** [comment]
@mattben great, these now look more in sync..
