### ISSUE TITLE
publications page issues

### ISSUE THREAD

**Issue by durack1** [PCMDI/pcmdi.github.io#85]
@mattben I've tried unsuccessfully to fix some issues with the https://github.com/PCMDI/pcmdi.github.io/blob/master/publications.md page - can you please take a peek and determine where the syntax went wrong?

It would also be good to sort these entries per year alphabetically, it seems that when these were generated no order was imposed at the time..

Alternatively, is it easier to provide DOIs and get these fields automatically generated? It might be cleaner in the long-term..?

**Comment by durack1** [comment]
@mattben any updates on this to?

**Comment by mattben** [comment]
O gosh that is a page of text. 
* I'll look through it and fix the syntax
* I'll contact @James-Crean / look for the DOI page generator.
* Using JavaScript we could put the list in to an array and attempt to sort it on page generation (not sure how long the page would take to load.)

**Comment by durack1** [comment]
@mattben if it worked, we could also incorporate the Altmetric info for each of these DOIs, so adding in `<div data-badge-popover="right" data-badge-type="2" data-doi="10.1038/nclimate2946" data-hide-no-mentions="true" class="altmetric-embed"></div>` with the DOI entry obtained from each page entry - it then generates the button shown [here](http://pcmdi.github.io/about/staff/durack/publication.html) and can be further customised, see [here](https://api.altmetric.com/embeds.html)

**Comment by mattben** [comment]
@durack1 I've cleaned up the file formate and the page looks better. d0f892cf8739a271153788d41ad3c9f2f8bdf011

`Sperber, K.R., 2003: Propagation and the vertical structure of the Madden-Julian Oscillation. Mon. Wea. Rev., 131, 3018â€“3037, doi: 10.1175/1520-0493(2003)131<3018:PATVSO>2.0.CO;2.`

the `â€` are in the actually file, this is not a browser interpretation error. At some point someone will have to manually fix them.

**Comment by durack1** [comment]
@mattben this publications page looks alot better now.. I wonder did @James-Crean get back to you about the DOI page generator, and the ability to sort alphabetically by year?

**Comment by mattben** [comment]
to be honest I don't know why its different, maybe it was because the site was out of sync with the repo for a little bit, or the web lord blessed us. 
James is in school, I won't be able to bug him until his start date in June 17

**Comment by durack1** [comment]
@mattben @hoang1 there was a [new commit 5hrs ago](https://github.com/PCMDI/pcmdi.github.io/commit/3dfbda566de75f4e28b3cce050075b7a6a1b0201) that doesn't appear to have propagated across to the live site - can you query what happened?

**Comment by mattben** [comment]
comparing the pagehttps://pcmdi.llnl.gov/home/publications.html with the commit different it seems to have taken. I searched the page for `8965-8987` and found the pub you changed. i'm using safari, I also checked the server and everything seems to have run correctly (git pull && jekyll b)

**Comment by durack1** [comment]
@mattben you're absolutely right a `command-R` gets me to the updated page too..

Are you happy to close this issue then, we seem to have a bunch of stuff above that is very poorly defined as a defined "issue"

**Comment by mattben** [comment]
@durack1 agreed. Please open new issues if updating seems to fail in the future.

**Comment by durack1** [comment]
@mattben the sorting and DOI submission info [noted above](https://github.com/PCMDI/pcmdi.github.io/issues/85#issuecomment-256365097) - did you want to create a new issue for each?

**Comment by durack1** [comment]
@mattben it seems we have another problem with changes not propagating..

So the [live page](https://pcmdi.llnl.gov/home/about/staff/durack/publication.html) shows: 

 Co-authored publications:

Ivanova, Detelina, Peter J. Gleckler, Karl E. Taylor, Paul J. Durack and Kate Marvel (2016) A Holistic Approach for Gauging Model Biases in Sea Ice Distribution: Moving beyond the Total Sea Ice Extent to Rectify Compensating Errors, Journal of Climate. **In press**. DOI: 10.1175/JCLI-D-16-0026.1 


[Should be](http://pcmdi.github.io/about/staff/durack/publication.html):

 Co-authored publications:

Ivanova, Detelina, Peter J. Gleckler, Karl E. Taylor, Paul J. Durack and Kate Marvel (2016) A Holistic Approach for Gauging Model Biases in Sea Ice Distribution: Moving beyond the Total Sea Ice Extent to Rectify Compensating Errors, Journal of Climate, **29 (24), pp 8965-8987**. DOI: 10.1175/JCLI-D-16-0026.1

**Comment by mattben** [comment]
This issues has collected a few issues and is being closed.

1. publications page issues (closed: corrected)
2.  DOI page generator, and the ability to sort alphabetically by year (new issue https://github.com/PCMDI/pcmdi.github.io/issues/98 please update)
3. site not updating (closed see https://github.com/PCMDI/pcmdi.github.io/issues/88)
