### ISSUE TITLE
program highlights page not updating

### ISSUE THREAD

**Issue by durack1** [PCMDI/pcmdi.github.io#86]
@mattben it seems that the updated page on github:
http://pcmdi.github.io/researchHighlights.html
is not updating to the site:
https://pcmdi.llnl.gov/home/researchHighlights.html

Can you please investigate this?

**Comment by durack1** [comment]
@mattben any updates on this?

**Comment by durack1** [comment]
@mattben it also seems that the page https://pcmdi.llnl.gov/home/about/staff/durack/publication.html is not updating, so the:
github version:
http://pcmdi.github.io/about/staff/durack/publication.html
And the site version:
https://pcmdi.llnl.gov/home/about/staff/durack/publication.html

Aren't in sync - I think this could be a problem across many of the site pages..

**Comment by mattben** [comment]
@durack1 we'll need to talk to @hoang1 and @sashakames about why the auto update cron is not working. I'm not sure why. 

`0 * * * * cd /var/www/pcmdi.github.io/ && git pull && jekyll b`

**Comment by hoang1** [comment]
This is on pcmdi6, correct?

**Comment by mattben** [comment]
@hoang1 no its on pcmdi.llnl.gov (the esgf node FKA pcmdi9)

**Comment by hoang1** [comment]
Let me check............Tony
________________________________

**Comment by hoang1** [comment]
Hi Matthew,


I encountered errors (below) when I tried running "jekyll b”; any ideas?……………Tony


[root@pcmdi cron]# cd /var/www/pcmdi.github.io/

[root@pcmdi pcmdi.github.io]# git pull

remote: Counting objects: 6, done.

remote: Compressing objects: 100% (6/6), done.

remote: Total 6 (delta 2), reused 0 (delta 0), pack-reused 0

Unpacking objects: 100% (6/6), done.

From https://github.com/PCMDI/pcmdi.github.io

   5c4d06d..4dde44d  master     -> origin/master

Auto-merging publications.md

Merge made by recursive.

 publications.md |   30 +++++++++++++++---------------

 1 files changed, 15 insertions(+), 15 deletions(-)

[root@pcmdi pcmdi.github.io]# jekyll b

Configuration file: /var/www/pcmdi.github.io/_config.yml

            Source: /var/www/pcmdi.github.io

       Destination: /var/www/pcmdi.github.io/_site

 Incremental build: disabled. Enable with --incremental

      Generating...

Error reading file /var/www/pcmdi.github.io/_layouts/santer_GRL_2015.png: invalid byte sequence in UTF-8

Error reading file /var/www/pcmdi.github.io/projects/amip/DIAGSUBS/sp5.html: (<unknown>): mapping values are not allowed in this context at line 3 column 37

Error reading file /var/www/pcmdi.github.io/projects/amip/DIAGSUBS/sp11.html: (<unknown>): mapping values are not allowed in this context at line 3 column 25

Error reading file /var/www/pcmdi.github.io/projects/amip/home/history/sp_further_info.html: (<unknown>): mapping values are not allowed in this context at line 3 column 37

Error reading file /var/www/pcmdi.github.io/projects/amip/AMIP2EXPDSN/BCS/amip2bcs.html: (<unknown>): mapping values are not allowed in this context at line 3 column 6

Error reading file /var/www/pcmdi.github.io/projects/amip/AMIP1/index.html: (<unknown>): mapping values are not allowed in this context at line 3 column 38

Error reading file /var/www/pcmdi.github.io/projects/amip/AMIP1/sp_further_info.html: (<unknown>): mapping values are not allowed in this context at line 3 column 38

                    done in 27.895 seconds.

 Auto-regeneration: disabled. Use --watch to enable.

[root@pcmdi pcmdi.github.io]#

**Comment by mattben** [comment]
I get them too, its html thats embed from the old CMS (Content Management System) they don't break the build or stop the page from rendering. At some point go through those pages and cleaning up there HTML is not a bad idea.

**Comment by durack1** [comment]
@mattben these two sites now look identical to me.. So I think this issue is solve, is the cronjob fixed so that any changes in the repo migrate to https://pcmdi.llnl.gov/home?

**Comment by mattben** [comment]
I think so too, I just double checked, both look good i'll close, woot closed issues!
