### ISSUE TITLE
www domain not forwarding

### ISSUE THREAD

**Issue by durack1** [PCMDI/pcmdi.github.io#87]
@mattben @hoang1 I just pointed my browser to https://www.pcmdi.llnl.gov/home and it doesn't redirect to https://pcmdi.llnl.gov/home/ - This should be fixed (as all other www prefixed URLs)

**Comment by mattben** [comment]
@durack1 who still uses www as a prefix? Noobs! I'll fix it

**Comment by durack1** [comment]
@mattben I know it's kinda <2000's but would be good to clean up.. It'll also ease the transition from www-pcmdi.llnl.gov when the redirect occurs..

**Comment by chaosphere2112** [comment]
@durack1 TLDR: the lab doesn't support "." in subdomains.

Domain names are split into three portions; the top level domain (TLD)– in our case, `gov`– the domain– `llnl`– and the subdomain– `pcmdi`, or `aims`, or `www`. Putting additional `<blah>.`'s prior to the subdomain is technically possible for normal DNS setups, but don't actually mean anything with regards to name servers; it refers to the entire section prior to the domain as a single entry. That means that in DNS, "www.pcmdi" is a distinct subdomain, and "pcmdi" is a distinct subdomain. The lab's DNS system does not allow us to put "." in subdomains, for "reasons". So, we can't really do this.

**Comment by mattben** [comment]
👍

**Comment by durack1** [comment]
@chaosphere2112 @mattben well the easiest thing would be a global redirect of www-pcmdi.llnl.gov to pcmdi.llnl.gov/home. The existing (old) site is at http://www-pcmdi.llnl.gov/

We also have cmip-pcmdi.llnl.gov

@taylor13 do you have a perspective to share here?

**Comment by chaosphere2112** [comment]
That should be no problem... we'll just have tony update the DNS entry for www-pcmdi, and use Apache to redirect appropriately.

**Comment by mattben** [comment]
@durack1 @taylor13 are you ready to take the old sites off line? If so I can get those both redirected today.

**Comment by hoang1** [comment]
www-pcmdi.llnl.gov is an alias for rainbow.llnl.gov now; I don't think I need to do anything, correct?

Tony
________________________________

**Comment by durack1** [comment]
@mattben I think we're close, I do wonder what else is required before this site is "blessed" however - do we need an LLNL-WEB number/approval
![161117_pcmdi](https://cloud.githubusercontent.com/assets/3229632/20401698/bbd25c18-acae-11e6-8e17-1d7cbd7c5182.png)

**Comment by mattben** [comment]
good catch `UCRL-WEB-152471`

**Comment by durack1** [comment]
@mattben I wonder if we need to go through the approval process again - the UCRL-WEB is many years old..?

**Comment by mattben** [comment]
I'm not sure of all the policy.  ¯\_(ツ)_/¯

**Comment by durack1** [comment]
@mattben regarding the forwarding the `Old Site` link on the new page redirects to https://pcmdi.llnl.gov/home - in some ways it would be nice to keep the old site available just in case we have missed migrating something

**Comment by chaosphere2112** [comment]
I believe it should be possible to just forward `http://www-pcmdi.llnl.gov/` to the new location and let everything else go through to the old stuff

**Comment by taylor13** [comment]
*  we need to make sure that on https://pcmdi.llnl.gov/home/ the link to "old site" goes to our old site and doesn't get forwarded to https://pcmdi.llnl.gov/home/
*  We need to include on https://pcmdi.llnl.gov/home/ two links near the top of the page which are identified as "Related LLNL Projects"; one should say "CAPT" and point to  http://www-pcmdi.llnl.gov/projects/capt/index.php ; the other should say "Cloud Feedbacks" and point to   http://www-pcmdi.llnl.gov/projects/cloud_feedbacks/index.php . 
*  Once we move to the new site, will entering something like http://cmip-pcmdi.llnl.gov/cmip5/guide_to_cmip5.html (an old site address) take me to https://pcmdi.llnl.gov/home/projects/cmip5/  (the corresponding new site address)?

**Comment by mattben** [comment]
@durack1 @taylor13 @hoang1 @chaosphere2112 

This issues now seems to be holding a few issues. Heres the run down and why I've closed this issues.

1. www domain not forwarding (closed: lab domain policy)
2. domain redirecting (closed: pcmdi.llnl.gov will be used asap)
3. LLNL-WEB number/approval (closed: site has one, if a updated one is desired, please request an IR review)
4. old site (closed: once pcmdi.llnl.gov is up, www-pcmdi.llnl.gov will point to the new site as a redirect. the old site can live under a secret url like old-pcmdi.llnl.gov)
