### ISSUE TITLE
New directories/files not propagating

### ISSUE THREAD

**Issue by durack1** [PCMDI/pcmdi.github.io#88]
@mattben @hoang1 I have just added a new subdir [`CMIP/index.html`](https://github.com/PCMDI/pcmdi.github.io/blob/master/CMIP6/index.html) in the repo and this doesn't appear to be propagating to https://pcmdi.llnl.gov/home

Can you guys take a peek at the cronjob and see if something is wrong?

**Comment by durack1** [comment]
@taylor13 pinging you

**Comment by mattben** [comment]
@durack1 I will re check the server and the site at 3:01 pm. Looks like your commit was 43 mins ago so around 2:05pm and the cron runs every hour. This is a perfect test to make sure the cron is working though since we've had issues in the past.

**Comment by durack1** [comment]
@mattben great, thanks for the heads up.. I wonder if there is some way of indicating a cronjob status in the repo, so a file that includes the latest cron timestamp? Would be a nice way to clarify whether things are operating as we expect

**Comment by durack1** [comment]
@mattben looks like [`http://pcmdi.llnl.gov/home/CMIP6`](http://pcmdi.llnl.gov/home/CMIP6) still isn't there to me.. Do we have another cron job bug?

**Comment by mattben** [comment]
@durack1 not this time thank goodness. This time Jekyll broke for two reasons, one the pages that had errors, I have finally fixed them all and just pushed that commit to the repo. The second reason was file permissions all files need a 644 permission or higher for jekyll to include them in this case https://pcmdi.llnl.gov/home/projects/cmip6/index.html had a file permission of 640 and was skipped.

on the plus the cron job works 👍

**Comment by durack1** [comment]
@mattben ok thanks for the clarification - `chmod 644+` on all new files is something I was oblivious..

**Comment by mattben** [comment]
@durack1 its usually the standard.

**Comment by durack1** [comment]
@mattben it seems the same problem is occurring with [CMIP6/CitationRequirements6-0.md](https://github.com/PCMDI/pcmdi.github.io/blob/master/CMIP6/CitationRequirements6-0.md).

I just checked the perms and we have a `644` for both the `index.html` and `CitationRequirements6-0.md` files.. So what is wrong here?

**Comment by durack1** [comment]
@mattben can you take a peek at this, we're getting queries from external parties about this inactive web page

@taylor13

**Comment by durack1** [comment]
@mattben @hoang1 can either of you take a peek at this, we're getting queries from external parties about this inactive web page and we really need to clean this up and get things operating correctly.. I have checked all the permissions, so not sure what the issue is now

@taylor13

**Comment by mattben** [comment]
@durack1 @hoang1 @taylor13 

pcmdi.llnl.gov seems to be under an update I'll check with @sashakames. It seems that when the cronjob does a `git pull` its default file permission is 600 which is strange. Once the server is working the site should be back to normal. @hoang1 how do I change the default new file permissions?

**Comment by hoang1** [comment]
I'll check with Sasha...........Tony
________________________________

**Comment by durack1** [comment]
@mattben @hoang1 the `umask` is the way around setting system-wide default permissions.. But this would have to be done with the IT fiddlers in mind which may reset the system-wide `umask` if you change it.. These links might be useful references
http://unix.stackexchange.com/questions/1314/how-to-set-default-file-permissions-for-all-folders-files-in-a-directory
https://www.cyberciti.biz/tips/understanding-linux-unix-umask-value-usage.html

**Comment by durack1** [comment]
@mattben to solve this permanently, could you add a `chmod 644 -R *` to the cronjob - that would then solve all the problems persistently.. And get us back up and running.. I see no reason why anything would need to be executable on the site.. I suppose directories would need to be `755` so they can be traversed..

**Comment by mattben** [comment]
@durack1 I'd want to run automated file permission changes by @hoang1 first. It just feels like a security vulnerability.

**Comment by hoang1** [comment]
Hi Matthew,

644 permission seems reasonable and not a security  vuln.....so you can go ahead and add the line chmod -R 644 * to the cron job.

Tony
________________________________

**Comment by durack1** [comment]
@mattben @hoang1 yet another instance of the cronjob not working:
http://pcmdi.github.io/CMIP6/OMIP/ should be found at
https://pcmdi.llnl.gov/home/CMIP6/OMIP/
Can you folks please take a peek at this too..

@taylor13 pinging you here

**Comment by mattben** [comment]
@durack1 @hoang1 @taylor13 is the new pcmdi server ready?

**Comment by hoang1** [comment]
Paul,

I loaded the OS on the new server; I will ask Matthew Harris to check and make sure all the needed/necessary software is there before we can deploy it.

Tony
________________________________

**Comment by durack1** [comment]
@mattben looks like the cron job is still not working, we have made a number of edits that just aren't propagating..

I queried @hoang1 and he managed to initialize a manual `git pull` and `jekyll b` so it's working manually (as I am sure you know) but it's just the cronjob that's not working..

From a peek at the cronjob it seems that:
```
[root@pcmdiweb log]# tail cron
Feb 23 15:45:01 pcmdiweb CROND[193337]: (root) CMD (/var/www/deploy.py > /tmp/pcmdiweb.txt)
Feb 23 15:50:01 pcmdiweb CROND[193395]: (root) CMD (/var/www/deploy.py > /tmp/pcmdiweb.txt)
Feb 23 15:50:01 pcmdiweb CROND[193396]: (root) CMD (/usr/lib64/sa/sa1 1 1)
Feb 23 15:55:01 pcmdiweb CROND[193454]: (root) CMD (/var/www/deploy.py > /tmp/pcmdiweb.txt)
Feb 23 16:00:01 pcmdiweb CROND[193513]: (root) CMD (/usr/lib64/sa/sa1 1 1)
Feb 23 16:00:01 pcmdiweb CROND[193514]: (root) CMD (/var/www/deploy.py > /tmp/pcmdiweb.txt)
Feb 23 16:01:01 pcmdiweb CROND[193533]: (root) CMD (run-parts /etc/cron.hourly)
Feb 23 16:01:01 pcmdiweb run-parts(/etc/cron.hourly)[193533]: starting 0anacron
Feb 23 16:01:01 pcmdiweb run-parts(/etc/cron.hourly)[193542]: finished 0anacron
Feb 23 16:01:43 pcmdiweb crontab[193650]: (root) LIST (root)
```
The file `/var/www/deploy.py` doesn't exist, rather it's located at `/var/www/pcmdi.github.io/deploy.py`. Also it seems that you have no environment setup in this `deploy.sh`:
```
[root@pcmdiweb harris112]# more /var/www/pcmdi.github.io/deploy.py 
#!/usr/bin/python
 
import os
import subprocess
 
subprocess.call(["git", "pull"])
# SHOULD ADD IN A PERMISSIONS WASH TO ENSURE THAT JEKYLL DOESN'T FAIL
subprocess.call(["jekyll", "b"])
```

So not sure that `git` or `jekyll` will be on the default `sh` path when it executes.. And also wash over the permissions so that no additional issues cause deployment problems

@dnadeau4 has some experience with this so he can chime in

**Comment by durack1** [comment]
From @dnadeau4
```
On 2/23/17, 4:58 PM, "Nadeau, Denis" wrote:

    This is what I have....
    
    #!/bin/bash
    # update a llnl.gov site using jekyll.
    # First argument is the directory to update
    # The script will call git pull and jekyll -b
    #
    
    source $HOME/.bashrc
    export GIT_SSL_NO_VERIFY=true
    argument=$1
    #
    echo "updating web site ${argument}"
    cd /var/www/${argument}
    git pull
    /usr/local/bin/jekyll b
```

**Comment by dnadeau4** [comment]
Crontab does not have an environment, it uses `sh`.   
This is the env I have from a cron job
```bash
HOME=/home/nadeau1
LOGNAME=nadeau1
PATH=/usr/bin:/bin
LANG=en_US.UTF-8
SHELL=/bin/sh
PWD=/home/nadeau1
```

**Comment by durack1** [comment]
thanks @dnadeau4

**Comment by taylor13** [comment]
@mattben @hoang1 Just to indicate priority here.  PCMDI is responsible for some critical CMIP6 information that should be posted right away on our *new* website (so folks won't later have to change any links).  As chair of the WGCM Infrastructure Panel, I would like to be able to point to a document at https://pcmdi.llnl.gov/CMIP6/TermsOfUse and have it work.   We have our next telco on Tuesday.  Can you make this happen?  Let me know if I can help in any way.

**Comment by durack1** [comment]
@sashakames pinging you here

**Comment by hoang1** [comment]
Hi Paul,


Sasha is on ESL today.


Tony

________________________________

**Comment by durack1** [comment]
@mattben any luck getting this sorted out? It seems that changes continue to not propagate to the live server http://pcmdiweb.llnl.gov

**Comment by mattben** [comment]
@durack1 @hoang1 @taylor13 @dnadeau4 

Now that I have the deploy script running correctly, lets return to the actually issue posted.
Paul can you verify that new directories/files are propagating as you expect please.

**Comment by durack1** [comment]
@mattben this appears to now be working, correctly propagating changes to display updated http://pcmdiweb.llnl.gov/projects/ page

**Comment by mattben** [comment]
👍
