### ISSUE TITLE
force line folding on code snippets

### ISSUE THREAD

**Issue by durack1** [PCMDI/pcmdi.github.io#90]
The long lines don't seem to be automagically folding, see https://pcmdi.llnl.gov/home/CMIP6/CitationRequirements6-0.html

It would be great if the CSS/templates can be tweaked to ensure that such folding occurs across all browsers. The screenshot below is from Firefox 50.1.0
![nofolding](https://cloud.githubusercontent.com/assets/3229632/22088860/02485e2c-dd9c-11e6-8370-8efabb2d7155.png)

**Comment by durack1** [comment]
@taylor13 pinging you here

**Comment by mattben** [comment]
@durack1 Can you add that file to the repo. My first guess though is that is in a code block which does not do line breaks by default. I'll have to play with the css or look for another element to use.

**Comment by durack1** [comment]
@mattben the file was renamed, it's now located (with an updated version) at https://github.com/PCMDI/pcmdi.github.io/tree/master/CMIP6/TermsOfUse

**Comment by durack1** [comment]
@mattben yep you're right it's marked as a code block

**Comment by James-Crean** [comment]
https://pcmdi.llnl.gov/CMIP6/TermsOfUse/TermsOfUse6-1.html

Seems fixed now. Closing.
