### ISSUE TITLE
www-pcmdi.llnl.gov not accessible

### ISSUE THREAD

**Issue by durack1** [PCMDI/pcmdi.github.io#91]
@hoang1 @mattben it seems that [http://www-pcmdi.llnl.gov/projects/amip/AMIP2EXPDSN/BCS/](http://www-pcmdi.llnl.gov/projects/amip/AMIP2EXPDSN/BCS/) is no longer accessible, just wondering what the status of the website(s) is?

@taylor13 pinging you here

**Comment by durack1** [comment]
Add to those URLs:
http://www-pcmdi.llnl.gov/about/staff/Durack/dump/industrialeraoceanwarming/160112_Gleckleretal_OceanWarmingDoubles-FAQs.pdf

http://www-pcmdi.llnl.gov/about/staff/Durack/dump/industrialeraoceanwarming/

**Comment by hoang1** [comment]
Things are back to normal now.............Tony

________________________________

**Comment by hoang1** [comment]
It's accessible now.....Problem was the root-document was not available due to nfs issue........Tony

________________________________

**Comment by durack1** [comment]
@hoang1 thanks for getting us back online! @mattben when will you be able to allocate some time to the website migration? We're hoping to get this moving as it's been some month now..

@taylor13

**Comment by durack1** [comment]
Thanks @hoang1 closing this
