### ISSUE TITLE
change in license statement needed

### ISSUE THREAD

**Issue by taylor13** [PCMDI/pcmdi.github.io#97]
Please replace in license statement (in TermsOfUse6-1.md)  "Use of the data must be acknowledged following guidelines found at https://pcmdi.llnl.gov/home/CMIP6/CitationRequirements6-0.html." with "Consult https://pcmdi.llnl.gov/CMIP6/TermsOfUse for terms of use governing CMIP6 output, including citation requirements and proper acknowledgment."

**Comment by durack1** [comment]
@taylor13 is this all fixed in https://github.com/PCMDI/pcmdi.github.io/pull/96/files? So we just need to merge that pull request (PR)?

**Comment by taylor13** [comment]
@durack1 I don't know.  I'm confused about how this gets done.  I made some changes around 5:30 last night.   Then I think I wrote the above comment.   If the changes  at the link you pointed to are consistent with the comment, then I guess merging is all that's required.  Unless you want to change the filename to a new version number.

**Comment by durack1** [comment]
@taylor13 yep the edited file at https://github.com/PCMDI/pcmdi.github.io/pull/96/files includes "`Consult https://pcmdi.llnl.gov/CMIP6/TermsOfUse`" so I think a merge and we're good to close this

**Comment by durack1** [comment]
Fixed by #96
