### ISSUE TITLE
publications.md

### ISSUE THREAD

**Issue by mattben** [PCMDI/pcmdi.github.io#98]
* DOI page generator script location and how to use @James-Crean 
* The page needs JS with the ability to sort alphabetically and by year

* This may be a non issues as @reshel3 is moving all this old static listing to the new publication site https://cmip-publications.llnl.gov/search?type=project&option=CMIP5

**Comment by James-Crean** [comment]
Is [this](https://github.com/James-Crean/doi-converter) the DOI converter you were thinking of?

**Comment by durack1** [comment]
@James-Crean does the referenced convertor take a doi and hand back a formatted string object that can be dropped into confluence? If yes, then this is exactly what we were hoping existed..

**Comment by durack1** [comment]
This should be closed, https://cmip-publications.llnl.gov/ is working great
